apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-image
  labels:
    app: debug-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-image
  template:
    metadata:
      labels:
        app: debug-image
    spec:
      containers:
      - image: ghcr.io/xiaoxiaosn/debug-image:latest
        name: debug-image
        command:
          - sleep
          - infinity
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
          - name: host
            mountPath: /host
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          runAsUser: 0
      volumes:
        - name: host
          hostPath:
            path: /
